/**
 * HTML template functions for ARD PDF documents.
 * Mirrors backend/app/shared/ard_documents.py using Puppeteer instead of xhtml2pdf.
 */
import QRCode from 'qrcode'
import bwipjs from 'bwip-js'

// ── Palette ───────────────────────────────────────────────────────────────────
const NAVY = '#1E3A5F'
const VIOLET = '#7C3AED'
const SLATE = '#475569'
const DARK = '#1E293B'
const GREEN = '#166534'

// ── Shared CSS ────────────────────────────────────────────────────────────────
const BASE_CSS = `
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: Arial, sans-serif; font-size: 9pt; color: ${DARK}; background: #fff; }
  h1 { font-size: 14pt; color: ${NAVY}; }
  h2 { font-size: 11pt; color: ${NAVY}; margin-bottom: 4px; }
  h3 { font-size: 10pt; color: ${SLATE}; margin-bottom: 4px; }
  table { width: 100%; border-collapse: collapse; margin-bottom: 10px; }
  th { background: ${NAVY}; color: #fff; padding: 5px 7px; text-align: left; font-size: 8.5pt; }
  td { padding: 4px 7px; border: 1px solid #d1d5db; font-size: 8.5pt; }
  tr:nth-child(even) td { background: #f8fafc; }
  .page-break { page-break-after: always; }
  .label { color: ${SLATE}; font-size: 8pt; font-weight: bold; text-transform: uppercase; }
  .badge { display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 8pt; font-weight: bold; }
  .header-block { border-bottom: 2px solid ${NAVY}; padding-bottom: 8px; margin-bottom: 14px; display: flex; justify-content: space-between; align-items: flex-start; }
  .footer { margin-top: 20px; border-top: 1px solid #d1d5db; padding-top: 6px; color: ${SLATE}; font-size: 7.5pt; text-align: center; }
  .meta-table td:first-child { background: #f1f5f9; font-weight: bold; width: 30%; }
  .oos td.oos-val { color: #dc2626; font-weight: bold; background: #fef2f2; }
  .section-title { background: ${VIOLET}; color: #fff; padding: 4px 8px; font-size: 9pt; font-weight: bold; margin: 10px 0 4px; }
`

function wrap(title: string, body: string): string {
  const ts = new Date().toLocaleString('en-IN')
  return `<!DOCTYPE html><html><head><meta charset="UTF-8">
  <title>${title}</title>
  <style>${BASE_CSS}</style>
  </head><body>
  ${body}
  <div class="footer">Generated by Laurus ELN &nbsp;·&nbsp; ${ts} &nbsp;·&nbsp; Confidential</div>
  </body></html>`
}

function statusBadge(status: string): string {
  const colors: Record<string, string> = {
    APPROVED: '#166534', SUBMITTED: '#1d4ed8', DRAFT: '#6b7280',
    REJECTED: '#991b1b', PENDING: '#92400e', COMPLETED: '#166534',
    RECEIVED: '#065f46', REGISTERED: '#1e3a8a', WITHDRAWN: '#4b5563',
  }
  const bg = colors[status?.toUpperCase()] ?? '#6b7280'
  return `<span class="badge" style="background:${bg};color:#fff">${status ?? ''}</span>`
}

async function qrDataUri(data: string): Promise<string> {
  return QRCode.toDataURL(data, { width: 80, margin: 1 })
}

async function barcodeDataUri(data: string): Promise<string> {
  try {
    const png = await bwipjs.toBuffer({ bcid: 'code128', text: data, scale: 2, height: 8, includetext: true, textxalign: 'center' })
    return `data:image/png;base64,${png.toString('base64')}`
  } catch {
    return ''
  }
}

// ── ATR Summary ───────────────────────────────────────────────────────────────
export async function atrSummaryHtml(form: any, company = 'Laurus Labs'): Promise<string> {
  const qr = await qrDataUri(`ATR:${form.arNo ?? form.id}`)
  const meta = [
    ['AR No', form.arNo ?? '—'], ['Status', statusBadge(form.status)],
    ['Project Code', form.projectCode ?? '—'], ['Project Name', form.projectName ?? '—'],
    ['Sample Code', form.sampleCode ?? '—'], ['Batch No', form.batchNo ?? '—'],
    ['Submitted By', form.submittedBy ?? '—'], ['Submitted At', form.submittedAt ? new Date(form.submittedAt).toLocaleDateString('en-IN') : '—'],
    ['Priority', form.priority ?? 'NORMAL'], ['Department', form.department ?? '—'],
  ]
  const metaRows = meta.map(([k, v]) => `<tr><td class="label">${k}</td><td>${v}</td></tr>`).join('')

  const tests: any[] = form.testRequests ?? []
  const testRows = tests.map((t: any) => `<tr>
    <td>${t.testName ?? t.technique ?? '—'}</td>
    <td>${t.sampleLabel ?? '—'}</td>
    <td>${t.specification ?? '—'}</td>
    <td>${statusBadge(t.status)}</td>
  </tr>`).join('')

  const body = `
    <div class="header-block">
      <div>
        <div class="label">${company}</div>
        <h1>Analytical Request (ATR)</h1>
        <div style="color:${SLATE};font-size:9pt;margin-top:4px">${form.arNo ?? 'Draft'}</div>
      </div>
      <img src="${qr}" width="80" height="80"/>
    </div>
    <table class="meta-table"><tbody>${metaRows}</tbody></table>
    <h2>Test Requests</h2>
    <table>
      <thead><tr><th>Test / Technique</th><th>Sample Label</th><th>Specification</th><th>Status</th></tr></thead>
      <tbody>${testRows || '<tr><td colspan="4">No test requests</td></tr>'}</tbody>
    </table>`
  return wrap(`ATR ${form.arNo ?? ''}`, body)
}

// ── ATR Certificate of Analysis ───────────────────────────────────────────────
export async function atrCoaHtml(form: any, company = 'Laurus Labs'): Promise<string> {
  const tests: any[] = form.testRequests ?? []
  const hasOos = tests.some((t: any) => t.isOos || t.result === 'FAIL')

  const testRows = tests.map((t: any) => {
    const oos = t.isOos || t.result === 'FAIL'
    return `<tr${oos ? ' class="oos"' : ''}>
      <td>${t.testName ?? t.technique ?? '—'}</td>
      <td>${t.specification ?? '—'}</td>
      <td class="${oos ? 'oos-val' : ''}">${t.resultValue ?? '—'}</td>
      <td>${t.units ?? '—'}</td>
      <td>${statusBadge(t.status)}</td>
    </tr>`
  }).join('')

  const body = `
    <div class="header-block">
      <div>
        <div class="label">${company}</div>
        <h1>Certificate of Analysis</h1>
        <div style="color:${SLATE};font-size:9pt;margin-top:4px">${form.arNo ?? '—'} · ${form.sampleCode ?? ''}</div>
      </div>
    </div>
    <table class="meta-table"><tbody>
      <tr><td class="label">Batch No</td><td>${form.batchNo ?? '—'}</td></tr>
      <tr><td class="label">Product</td><td>${form.projectName ?? '—'}</td></tr>
      <tr><td class="label">Report Date</td><td>${new Date().toLocaleDateString('en-IN')}</td></tr>
      ${hasOos ? '<tr><td colspan="2" style="color:#dc2626;font-weight:bold">⚠ One or more results are out-of-specification (OOS)</td></tr>' : ''}
    </tbody></table>
    <h2>Results</h2>
    <table>
      <thead><tr><th>Test</th><th>Specification</th><th>Result</th><th>Units</th><th>Status</th></tr></thead>
      <tbody>${testRows || '<tr><td colspan="5">No results</td></tr>'}</tbody>
    </table>
    <table style="margin-top:20px">
      <thead><tr><th>Prepared By</th><th>Reviewed By</th><th>Approved By</th></tr></thead>
      <tbody><tr>
        <td style="height:50px">${form.preparedBy ?? ''}<br/><br/><small>Sign &amp; Date</small></td>
        <td>${form.reviewedBy ?? ''}<br/><br/><small>Sign &amp; Date</small></td>
        <td>${form.approvedBy ?? ''}<br/><br/><small>Sign &amp; Date</small></td>
      </tr></tbody>
    </table>`
  return wrap(`COA ${form.arNo ?? ''}`, body)
}

// ── ATR Detailed ──────────────────────────────────────────────────────────────
export async function atrDetailedHtml(form: any, company = 'Laurus Labs'): Promise<string> {
  const tests: any[] = form.testRequests ?? []
  const sections = tests.map((t: any) => {
    const obs = t.observations ?? {}
    const obsRows = Object.entries(obs).map(([k, v]) => `<tr><td class="label">${k}</td><td>${v ?? ''}</td></tr>`).join('')
    return `
      <h3 style="margin-top:14px;color:${NAVY}">${t.testName ?? t.technique ?? 'Test'}</h3>
      <table class="meta-table"><tbody>
        <tr><td class="label">Specification</td><td>${t.specification ?? '—'}</td></tr>
        <tr><td class="label">Result Value</td><td>${t.resultValue ?? '—'} ${t.units ?? ''}</td></tr>
        <tr><td class="label">Status</td><td>${statusBadge(t.status)}</td></tr>
        ${obsRows}
      </tbody></table>`
  }).join('')

  const body = `
    <div class="header-block">
      <div><div class="label">${company}</div><h1>ATR Detailed Report</h1>
        <div style="color:${SLATE};font-size:9pt;margin-top:4px">${form.arNo ?? '—'}</div>
      </div>
    </div>
    ${sections || '<p>No test data available.</p>'}`
  return wrap(`ATR Detailed ${form.arNo ?? ''}`, body)
}

// ── ARD Experiment Report ─────────────────────────────────────────────────────
export function ardExperimentReportHtml(
  exp: any, notebook: any, project: any,
  creatorName: string, company = 'Laurus Labs'
): string {
  // exp.sections is stored as an object keyed by section id (not an array) —
  // calling .map on it threw and made every PDF export fail silently (caught
  // upstream and surfaced as a generic 500).
  const rawSections = notebook?.templateSnapshot?.sections ?? exp.sections ?? []
  const sections: any[] = Array.isArray(rawSections) ? rawSections : Object.values(rawSections || {})

  function renderSection(sec: any): string {
    const kind = sec.type ?? sec.kind ?? ''
    const title = sec.title ?? sec.label ?? kind
    const value = sec.value ?? sec.data ?? null

    if (kind === 'richtext' || kind === 'conclusion' || kind === 'disposition' || kind === 'observations') {
      return `<div class="section-title">${title}</div>
        <div style="padding:6px;border:1px solid #e2e8f0;margin-bottom:8px;font-size:9pt">${value ?? ''}</div>`
    }
    if (kind === 'table' && Array.isArray(value)) {
      const headers = value[0] ? Object.keys(value[0]) : []
      const thRow = headers.map(h => `<th>${h}</th>`).join('')
      const rows = value.map((row: any) =>
        `<tr>${headers.map(h => `<td>${row[h] ?? ''}</td>`).join('')}</tr>`
      ).join('')
      return `<div class="section-title">${title}</div>
        <table><thead><tr>${thRow}</tr></thead><tbody>${rows}</tbody></table>`
    }
    if (kind === 'params' && typeof value === 'object' && value) {
      const rows = Object.entries(value).map(([k, v]) =>
        `<tr><td class="label">${k}</td><td>${v ?? ''}</td></tr>`
      ).join('')
      return `<div class="section-title">${title}</div>
        <table class="meta-table"><tbody>${rows}</tbody></table>`
    }
    if (value !== null && value !== undefined) {
      return `<div class="section-title">${title}</div>
        <div style="padding:6px 8px;border:1px solid #e2e8f0;margin-bottom:8px">${String(value)}</div>`
    }
    return ''
  }

  const sectionHtml = sections.map(renderSection).join('')
  const meta = [
    ['Project', project?.name ?? project?.code ?? '—'],
    ['Notebook', notebook?.code ?? notebook?.title ?? '—'],
    ['Experiment Code', exp.code ?? exp.id ?? '—'],
    ['Title', exp.title ?? '—'],
    ['Status', statusBadge(exp.status)],
    ['Submitted By', creatorName],
    ['Submitted At', exp.submittedAt ? new Date(exp.submittedAt).toLocaleDateString('en-IN') : '—'],
    ['Approved By', exp.approvedBy ?? '—'],
    ['Approved At', exp.approvedAt ? new Date(exp.approvedAt).toLocaleDateString('en-IN') : '—'],
    ['Generated', new Date().toLocaleString('en-IN')],
  ]
  const metaRows = meta.map(([k, v]) => `<tr><td class="label">${k}</td><td>${v}</td></tr>`).join('')

  const body = `
    <div class="header-block">
      <div><div class="label">${company}</div><h1>Experiment Report</h1>
        <div style="color:${SLATE};font-size:9pt;margin-top:4px">${exp.code ?? exp.id ?? '—'} · ${exp.title ?? ''}</div>
      </div>
    </div>
    <table class="meta-table"><tbody>${metaRows}</tbody></table>
    ${sectionHtml}`
  return wrap(`Experiment Report ${exp.code ?? ''}`, body)
}

// ── QC-TRF Summary ────────────────────────────────────────────────────────────
export async function qcTrfSummaryHtml(form: any, company = 'Laurus Labs'): Promise<string> {
  const barcode = form.formNo ? await barcodeDataUri(form.formNo) : ''
  const samples: any[] = form.sampleLines ?? []
  const tests: any[] = form.testRequests ?? []

  const sampleRows = samples.map((s: any) => `<tr>
    <td>${s.sampleCode ?? '—'}</td>
    <td>${s.batchNo ?? '—'}</td>
    <td>${s.quantity ?? '—'} ${s.units ?? ''}</td>
    <td>${s.storageCondition ?? '—'}</td>
  </tr>`).join('')

  const testRows = tests.map((t: any) => `<tr>
    <td>${t.testName ?? t.technique ?? '—'}</td>
    <td>${t.specification ?? '—'}</td>
    <td>${t.priority ?? 'NORMAL'}</td>
  </tr>`).join('')

  const meta = [
    ['Form No', form.formNo ?? '—'], ['Status', statusBadge(form.status)],
    ['Project Code', form.projectCode ?? '—'], ['Project Name', form.projectName ?? '—'],
    ['Submitted By', form.submittedBy ?? '—'],
    ['Submitted At', form.submittedAt ? new Date(form.submittedAt).toLocaleDateString('en-IN') : '—'],
    ['Remarks', form.remarks ?? '—'],
  ]
  const metaRows = meta.map(([k, v]) => `<tr><td class="label">${k}</td><td>${v}</td></tr>`).join('')

  const body = `
    <div class="header-block">
      <div><div class="label">${company}</div><h1>Quality Control Transfer Request</h1>
        <div style="color:${SLATE};font-size:9pt;margin-top:4px">${form.formNo ?? 'Draft'}</div>
      </div>
      ${barcode ? `<img src="${barcode}" style="height:40px"/>` : ''}
    </div>
    <table class="meta-table"><tbody>${metaRows}</tbody></table>
    <h2>Sample Lines</h2>
    <table>
      <thead><tr><th>Sample Code</th><th>Batch No</th><th>Quantity</th><th>Storage Condition</th></tr></thead>
      <tbody>${sampleRows || '<tr><td colspan="4">No samples</td></tr>'}</tbody>
    </table>
    <h2>Test Requests</h2>
    <table>
      <thead><tr><th>Test / Technique</th><th>Specification</th><th>Priority</th></tr></thead>
      <tbody>${testRows || '<tr><td colspan="3">No test requests</td></tr>'}</tbody>
    </table>`
  return wrap(`QC-TRF ${form.formNo ?? ''}`, body)
}

// ── ARD Notebook Report ───────────────────────────────────────────────────────
export function ardNotebookReportHtml(notebook: any, experiments: any[], company = 'Laurus Labs'): string {
  const expRows = experiments.map((e: any) => `<tr>
    <td>${e.code ?? e.id ?? '—'}</td>
    <td>${e.title ?? '—'}</td>
    <td>${statusBadge(e.status)}</td>
    <td>${e.createdAt ? new Date(e.createdAt).toLocaleDateString('en-IN') : '—'}</td>
    <td>${e.assignedTo ?? '—'}</td>
  </tr>`).join('')

  const meta = [
    ['Notebook Code', notebook.code ?? '—'],
    ['Title', notebook.title ?? '—'],
    ['Status', statusBadge(notebook.status)],
    ['Section', notebook.section ?? '—'],
    ['Opened', notebook.openedAt ? new Date(notebook.openedAt).toLocaleDateString('en-IN') : '—'],
    ['Closed', notebook.closedAt ? new Date(notebook.closedAt).toLocaleDateString('en-IN') : '—'],
    ['Total Experiments', String(experiments.length)],
  ]
  const metaRows = meta.map(([k, v]) => `<tr><td class="label">${k}</td><td>${v}</td></tr>`).join('')

  const body = `
    <div class="header-block">
      <div><div class="label">${company}</div><h1>Notebook Report</h1>
        <div style="color:${SLATE};font-size:9pt;margin-top:4px">${notebook.code ?? '—'}</div>
      </div>
    </div>
    <table class="meta-table"><tbody>${metaRows}</tbody></table>
    <h2>Experiments</h2>
    <table>
      <thead><tr><th>Code</th><th>Title</th><th>Status</th><th>Date</th><th>Assigned To</th></tr></thead>
      <tbody>${expRows || '<tr><td colspan="5">No experiments</td></tr>'}</tbody>
    </table>`
  return wrap(`Notebook Report ${notebook.code ?? ''}`, body)
}

// ── ARD Report (generic — wraps tabular report data) ──────────────────────────
export function ardReportHtml(reportName: string, headers: string[], rows: any[][], params: Record<string, string>, company = 'Laurus Labs'): string {
  const paramRows = Object.entries(params).filter(([, v]) => v)
    .map(([k, v]) => `<tr><td class="label">${k}</td><td>${v}</td></tr>`).join('')

  const thRow = headers.map(h => `<th>${h}</th>`).join('')
  const dataRows = rows.map(r =>
    `<tr>${r.map(c => `<td>${c ?? '—'}</td>`).join('')}</tr>`
  ).join('')

  const body = `
    <div class="header-block">
      <div><div class="label">${company}</div><h1>${reportName}</h1>
        <div style="color:${SLATE};font-size:9pt;margin-top:4px">Generated ${new Date().toLocaleString('en-IN')}</div>
      </div>
    </div>
    ${paramRows ? `<table class="meta-table"><tbody>${paramRows}</tbody></table>` : ''}
    <table>
      <thead><tr>${thRow}</tr></thead>
      <tbody>${dataRows || `<tr><td colspan="${headers.length}">No data</td></tr>`}</tbody>
    </table>`
  return wrap(reportName, body)
}

// ── ADC/CGT Experiment Report (replaces python-docx) ─────────────────────────
export function adcExperimentReportHtml(
  exp: any, notebook: any, project: any,
  approverName: string, submitterName: string, company = 'Laurus Labs'
): string {
  const sections: any[] = exp.templateSnapshot?.sections ?? notebook?.templateSnapshot?.sections ?? []

  function renderSection(sec: any): string {
    const kind = sec.type ?? sec.kind ?? 'field'
    const title = sec.title ?? sec.label ?? kind

    if (['richtext', 'text', 'observations', 'conclusion', 'disposition'].includes(kind)) {
      return `<div class="section-title">${title}</div>
        <div style="padding:8px;border:1px solid #e2e8f0;margin-bottom:8px">${sec.value ?? ''}</div>`
    }
    if (kind === 'table' && Array.isArray(sec.value)) {
      const headers = sec.value[0] ? Object.keys(sec.value[0]) : []
      const thRow = headers.map((h: string) => `<th>${h}</th>`).join('')
      const rows = sec.value.map((row: any) =>
        `<tr>${headers.map((h: string) => `<td>${row[h] ?? ''}</td>`).join('')}</tr>`
      ).join('')
      return `<div class="section-title">${title}</div>
        <table><thead><tr>${thRow}</tr></thead><tbody>${rows}</tbody></table>`
    }
    if (kind === 'js_sheet') {
      const fields: any[] = sec.fieldValues ?? []
      const rows = fields.map((f: any) =>
        `<tr><td class="label">${f.label ?? f.key ?? '—'}</td><td>${f.value ?? ''}</td></tr>`
      ).join('')
      return `<div class="section-title">${title}</div>
        <table class="meta-table"><tbody>${rows || '<tr><td colspan="2">No fields</td></tr>'}</tbody></table>`
    }
    return ''
  }

  const meta = [
    ['Project', project?.name ?? project?.projectName ?? '—'],
    ['Notebook', notebook?.code ?? notebook?.title ?? '—'],
    ['Experiment Code', exp.code ?? exp.experimentCode ?? '—'],
    ['Title', exp.title ?? '—'],
    ['Status', statusBadge(exp.status)],
    ['Submitted By', submitterName],
    ['Submitted At', exp.submittedAt ? new Date(exp.submittedAt).toLocaleDateString('en-IN') : '—'],
    ['Approved By', approverName],
    ['Approved At', exp.approvedAt ? new Date(exp.approvedAt).toLocaleDateString('en-IN') : '—'],
    ['Generated', new Date().toLocaleString('en-IN')],
  ]
  const metaRows = meta.map(([k, v]) => `<tr><td class="label">${k}</td><td>${v}</td></tr>`).join('')
  const sectionHtml = sections.map(renderSection).join('')

  const body = `
    <div class="header-block">
      <div><div class="label">${company}</div><h1>Experiment Report</h1>
        <div style="color:${SLATE};font-size:9pt;margin-top:4px">${exp.code ?? exp.experimentCode ?? '—'} · ${exp.title ?? ''}</div>
      </div>
    </div>
    <table class="meta-table"><tbody>${metaRows}</tbody></table>
    ${sectionHtml}`
  return wrap(`Experiment Report ${exp.code ?? ''}`, body)
}
