"""remove_redundant_version_number_from_history

Revision ID: 8145d321d174
Revises: 54d5062b27bf
Create Date: 2026-06-08 12:20:32.202875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8145d321d174'
down_revision: Union[str, None] = '54d5062b27bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experiment_history', 'version_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # server_default='1' prevents NOT NULL failure on rollback with existing rows
    op.add_column('experiment_history', sa.Column(
        'version_number', sa.SMALLINT(), autoincrement=False,
        nullable=False, server_default='1'
    ))
    # ### end Alembic commands ###
