"""add_missing_fields_versioning

Revision ID: 99c6cfdac31d
Revises: 58d8fa04abad
Create Date: 2026-06-08 12:03:04.902853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99c6cfdac31d'
down_revision: Union[str, None] = '58d8fa04abad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_attachments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.String(length=20), nullable=True),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('uploaded_by', sa.String(length=36), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('company_settings', sa.Column('short_name', sa.String(length=50), nullable=True))
    op.add_column('experiments', sa.Column('revision_note', sa.Text(), nullable=True))
    # server_default=sa.false() required — table may have existing rows
    op.add_column('notebook_permissions', sa.Column('can_clone',          sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('notebook_permissions', sa.Column('can_request_unlock', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('notebook_permissions', sa.Column('can_deactivate',     sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('projects', sa.Column('project_type', sa.String(length=20), nullable=True))
    op.add_column('projects', sa.Column('market', sa.String(length=50), nullable=True))
    op.add_column('projects', sa.Column('manager_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'projects', 'users', ['manager_id'], ['id'])
    op.add_column('routes', sa.Column('status', sa.String(length=20), nullable=False, server_default='ACTIVE'))
    op.add_column('stages', sa.Column('status', sa.String(length=20), nullable=False, server_default='ACTIVE'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stages', 'status')
    op.drop_column('routes', 'status')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'manager_id')
    op.drop_column('projects', 'market')
    op.drop_column('projects', 'project_type')
    op.drop_column('notebook_permissions', 'can_deactivate')
    op.drop_column('notebook_permissions', 'can_request_unlock')
    op.drop_column('notebook_permissions', 'can_clone')
    op.drop_column('experiments', 'revision_note')
    op.drop_column('company_settings', 'short_name')
    op.drop_table('project_attachments')
    # ### end Alembic commands ###
