"""comprehensive_model_fixes

Revision ID: aeb7b2f53360
Revises: 8145d321d174
Create Date: 2026-06-08 12:43:31.584975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aeb7b2f53360'
down_revision: Union[str, None] = '8145d321d174'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiment_comments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('experiment_id', sa.String(length=36), nullable=False),
    sa.Column('version_experiment_id', sa.String(length=36), nullable=True),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('comment_type', sa.String(length=30), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['experiment_comments.id'], ),
    sa.ForeignKeyConstraint(['version_experiment_id'], ['experiments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unlock_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('experiment_id', sa.String(length=36), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('requested_by', sa.String(length=36), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_by', sa.String(length=36), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('atr_attachments', 'file_size',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.BigInteger(),
               existing_nullable=True,
               postgresql_using='file_size::bigint')
    op.add_column('departments', sa.Column('created_by', sa.String(length=36), nullable=True))
    op.add_column('departments', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.text('NOW()')))
    op.create_foreign_key(None, 'departments', 'users', ['created_by'], ['id'])
    op.alter_column('experiment_attachments', 'file_size',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.BigInteger(),
               existing_nullable=True,
               postgresql_using='file_size::bigint')
    op.alter_column('experiment_parameters', 'value',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.add_column('experiments', sa.Column('is_latest_version', sa.Boolean(), nullable=False,
                  server_default=sa.true()))
    op.create_unique_constraint('uq_notebook_user_permission', 'notebook_permissions', ['notebook_id', 'user_id'])
    op.alter_column('project_attachments', 'file_size',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.BigInteger(),
               existing_nullable=True,
               postgresql_using='file_size::bigint')
    op.alter_column('projects', 'description',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_unique_constraint('uq_role_dept_privilege', 'role_privileges', ['role_id', 'department_id', 'privilege_key'])
    op.add_column('routes', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.text('NOW()')))
    op.add_column('stages', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.text('NOW()')))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('failed_login_count', sa.SmallInteger(), nullable=False,
                  server_default='0'))
    op.add_column('users', sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'failed_login_count')
    op.drop_column('users', 'last_login_at')
    op.drop_column('stages', 'updated_at')
    op.drop_column('routes', 'updated_at')
    op.drop_constraint('uq_role_dept_privilege', 'role_privileges', type_='unique')
    op.alter_column('projects', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
    op.alter_column('project_attachments', 'file_size',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.drop_constraint('uq_notebook_user_permission', 'notebook_permissions', type_='unique')
    op.drop_column('experiments', 'is_latest_version')
    op.alter_column('experiment_parameters', 'value',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('experiment_attachments', 'file_size',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.drop_column('departments', 'updated_at')
    op.drop_column('departments', 'created_by')
    op.alter_column('atr_attachments', 'file_size',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.drop_table('unlock_requests')
    op.drop_table('experiment_comments')
    # ### end Alembic commands ###
