"""sync_model_drift

Revision ID: da2536df0fed
Revises: b7d4e2f8a1c9
Create Date: 2026-06-11 11:08:33.291070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.sql import text

# revision identifiers, used by Alembic.
revision: str = 'da2536df0fed'
down_revision: Union[str, None] = 'b7d4e2f8a1c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop in FK-safe order: children before parents
    op.drop_index('ix_atr_test_results_test_id', table_name='atr_test_results')
    op.drop_table('atr_test_results')
    op.drop_index('ix_atr_attributes_atr_id', table_name='atr_attributes')
    op.drop_table('atr_attributes')
    op.drop_index('ix_atr_tests_atr_id', table_name='atr_tests')
    op.drop_table('atr_tests')
    op.drop_index('ix_atr_samples_atr_id', table_name='atr_samples')
    op.drop_table('atr_samples')
    op.drop_index('ix_project_attrs_project_id', table_name='project_attributes')
    op.drop_table('project_attributes')
    op.drop_table('milestone_predecessors')
    op.drop_index('ix_proj_param_tmpl_project_id', table_name='project_parameter_templates')
    op.drop_table('project_parameter_templates')
    op.drop_index('ix_stage_inputs_stage_id', table_name='stage_inputs')
    op.drop_table('stage_inputs')
    op.execute(text("UPDATE atr SET objectives = '' WHERE objectives IS NULL"))
    op.alter_column('atr', 'objectives',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_constraint('fk_atr_parent_atr', 'atr', type_='foreignkey')
    op.drop_constraint('fk_atr_parent_version', 'atr', type_='foreignkey')
    op.drop_constraint('fk_atr_accepted_by', 'atr', type_='foreignkey')
    op.drop_column('atr', 'clarification_requested_at')
    op.drop_column('atr', 'parent_version_id')
    op.drop_column('atr', 'is_standalone')
    op.drop_column('atr', 'parent_atr_id')
    op.drop_column('atr', 'accepted_at')
    op.drop_column('atr', 'atr_remarks')
    op.drop_column('atr', 'raised_on')
    op.drop_column('atr', 'form_type')
    op.drop_column('atr', 'clarification_remarks')
    op.drop_column('atr', 'ad_remarks')
    op.drop_column('atr', 'report_type')
    op.drop_column('atr', 'accepted_by')
    op.drop_column('atr_attachments', 'file_type')
    op.drop_column('atr_attachments', 'description')
    op.drop_constraint('atr_final_reports_atr_id_fkey', 'atr_final_reports', type_='foreignkey')
    op.create_foreign_key(None, 'atr_final_reports', 'atr', ['atr_id'], ['id'])
    op.alter_column('audit_log', 'target_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
    op.drop_index('idx_audit_log_created_at', table_name='audit_log')
    op.create_index('ix_audit_created_at', 'audit_log', ['created_at'], unique=False)
    op.create_index('ix_audit_module_at', 'audit_log', ['module', 'created_at'], unique=False)
    op.create_index('ix_audit_target', 'audit_log', ['target_type', 'target_id'], unique=False)
    op.create_index('ix_audit_user_at', 'audit_log', ['user_id', 'created_at'], unique=False)
    op.alter_column('departments', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.create_index('ix_exp_attach_exp_id', 'experiment_attachments', ['experiment_id'], unique=False)
    op.create_index('ix_exp_comments_exp_id', 'experiment_comments', ['experiment_id'], unique=False)
    op.alter_column('experiment_equipment', 'instrument_code',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_index('ix_exp_equipment_experiment_id', table_name='experiment_equipment')
    op.create_index('ix_exp_equip_exp_id', 'experiment_equipment', ['experiment_id'], unique=False)
    op.drop_constraint('experiment_equipment_experiment_id_fkey', 'experiment_equipment', type_='foreignkey')
    op.create_foreign_key(None, 'experiment_equipment', 'experiments', ['experiment_id'], ['id'])
    op.drop_constraint('experiment_excel_templates_experiment_id_fkey', 'experiment_excel_templates', type_='foreignkey')
    op.create_foreign_key(None, 'experiment_excel_templates', 'experiments', ['experiment_id'], ['id'])
    op.create_index('ix_exp_hist_action_at', 'experiment_history', ['action', 'action_at'], unique=False)
    op.create_index('ix_exp_hist_exp_id', 'experiment_history', ['experiment_id'], unique=False)
    op.alter_column('experiment_inputs', 'cas_no',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=True)
    op.alter_column('experiment_inputs', 'quantity',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Numeric(precision=12, scale=4),
               existing_nullable=True)
    op.alter_column('experiment_inputs', 'moles',
               existing_type=sa.NUMERIC(precision=12, scale=6),
               type_=sa.Numeric(precision=14, scale=8),
               existing_nullable=True)
    op.create_index('ix_exp_inputs_exp_id', 'experiment_inputs', ['experiment_id'], unique=False)
    op.execute(text("UPDATE experiment_parameters SET name = parameter_name WHERE name IS NULL AND parameter_name IS NOT NULL"))
    op.execute(text("UPDATE experiment_parameters SET name = 'Unknown' WHERE name IS NULL"))
    op.alter_column('experiment_parameters', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.create_index('ix_exp_params_exp_id', 'experiment_parameters', ['experiment_id'], unique=False)
    op.drop_column('experiment_parameters', 'parameter_name')
    op.drop_index('ix_exp_steps_experiment_id', table_name='experiment_steps')
    op.create_index('ix_exp_steps_exp_id', 'experiment_steps', ['experiment_id'], unique=False)
    op.drop_constraint('experiment_steps_experiment_id_fkey', 'experiment_steps', type_='foreignkey')
    op.create_foreign_key(None, 'experiment_steps', 'experiments', ['experiment_id'], ['id'])
    op.create_index('ix_exp_tlc_exp_id', 'experiment_tlc', ['experiment_id'], unique=False)
    op.drop_index('idx_experiments_created_by', table_name='experiments')
    op.drop_index('idx_experiments_notebook_id', table_name='experiments')
    op.drop_index('idx_experiments_status_latest', table_name='experiments')
    op.drop_index('idx_experiments_submitted_to', table_name='experiments')
    op.create_index('ix_exp_code', 'experiments', ['code'], unique=False)
    op.create_index('ix_exp_created_at', 'experiments', ['created_at'], unique=False)
    op.create_index('ix_exp_latest_version', 'experiments', ['is_latest_version'], unique=False)
    op.create_index('ix_exp_notebook_status', 'experiments', ['notebook_id', 'status'], unique=False)
    op.create_index('ix_exp_project_status', 'experiments', ['project_id', 'status'], unique=False)
    op.create_index('ix_exp_root', 'experiments', ['root_experiment_id'], unique=False)
    op.drop_index('ix_lookup_chemicals_name', table_name='lookup_chemicals')
    op.drop_column('lookup_instruments', 'location')
    op.drop_constraint('milestone_attachments_milestone_id_fkey', 'milestone_attachments', type_='foreignkey')
    op.create_foreign_key(None, 'milestone_attachments', 'milestones', ['milestone_id'], ['id'])
    op.drop_constraint('fk_ms_responsible', 'milestones', type_='foreignkey')
    op.drop_column('milestones', 'responsible_person_id')
    op.drop_column('milestones', 'actual_end_date')
    op.drop_column('milestones', 'sort_order')
    op.drop_column('milestones', 'planned_start_date')
    op.drop_column('milestones', 'description')
    op.drop_column('milestones', 'actual_start_date')
    op.add_column('notebook_permissions', sa.Column('can_submit', sa.Boolean(), nullable=True))
    op.add_column('notebook_permissions', sa.Column('can_export', sa.Boolean(), nullable=True))
    op.add_column('notebook_permissions', sa.Column('can_attach', sa.Boolean(), nullable=True))
    op.add_column('notebook_permissions', sa.Column('can_comment', sa.Boolean(), nullable=True))
    op.add_column('notebook_permissions', sa.Column('can_request_unlock', sa.Boolean(), nullable=True))
    op.execute(text("UPDATE notebook_permissions SET can_submit=false, can_export=false, can_attach=false, can_comment=false, can_request_unlock=false WHERE can_submit IS NULL"))
    op.alter_column('notebook_permissions', 'can_submit', nullable=False)
    op.alter_column('notebook_permissions', 'can_export', nullable=False)
    op.alter_column('notebook_permissions', 'can_attach', nullable=False)
    op.alter_column('notebook_permissions', 'can_comment', nullable=False)
    op.alter_column('notebook_permissions', 'can_request_unlock', nullable=False)
    op.drop_column('notebook_permissions', 'can_create')
    op.drop_column('notebook_permissions', 'can_req_unlock')
    op.drop_column('notebook_permissions', 'notify')
    op.alter_column('notebooks', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.drop_index('idx_password_reset_tokens_user_id', table_name='password_reset_tokens')
    op.drop_column('project_attachments', 'display_name')
    op.drop_column('project_attachments', 'description')
    op.drop_column('project_users', 'notify')
    op.drop_column('project_users', 'role_in_project')
    op.drop_constraint('fk_proj_deactivated_by', 'projects', type_='foreignkey')
    op.drop_constraint('fk_proj_closed_by', 'projects', type_='foreignkey')
    op.drop_column('projects', 'closed_by')
    op.drop_column('projects', 'closed_at')
    op.drop_column('projects', 'deactivated_at')
    op.drop_column('projects', 'deactivated_by')
    op.drop_index('idx_refresh_tokens_user_expires', table_name='refresh_tokens')
    op.drop_index('uq_role_priv_dept', table_name='role_privileges', postgresql_where='(department_id IS NOT NULL)')
    op.drop_index('uq_role_priv_global', table_name='role_privileges', postgresql_where='(department_id IS NULL)')
    op.execute(text("UPDATE roles SET created_at = NOW() WHERE created_at IS NULL"))
    op.alter_column('roles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('routes', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.drop_constraint('uq_routes_project_code', 'routes', type_='unique')
    op.drop_column('routes', 'scheme_image_path')
    op.alter_column('stages', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.drop_constraint('uq_stages_route_code', 'stages', type_='unique')
    op.drop_column('stages', 'scheme_image_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stages', sa.Column('scheme_image_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.create_unique_constraint('uq_stages_route_code', 'stages', ['route_id', 'code'])
    op.alter_column('stages', 'description',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.add_column('routes', sa.Column('scheme_image_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.create_unique_constraint('uq_routes_project_code', 'routes', ['project_id', 'code'])
    op.alter_column('routes', 'description',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('roles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.create_index('uq_role_priv_global', 'role_privileges', ['role_id', 'privilege_key'], unique=True, postgresql_where='(department_id IS NULL)')
    op.create_index('uq_role_priv_dept', 'role_privileges', ['role_id', 'department_id', 'privilege_key'], unique=True, postgresql_where='(department_id IS NOT NULL)')
    op.create_index('idx_refresh_tokens_user_expires', 'refresh_tokens', ['user_id', 'expires_at'], unique=False)
    op.add_column('projects', sa.Column('deactivated_by', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('deactivated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('closed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('closed_by', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_proj_closed_by', 'projects', 'users', ['closed_by'], ['id'])
    op.create_foreign_key('fk_proj_deactivated_by', 'projects', 'users', ['deactivated_by'], ['id'])
    op.add_column('project_users', sa.Column('role_in_project', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('project_users', sa.Column('notify', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('project_attachments', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('project_attachments', sa.Column('display_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_index('idx_password_reset_tokens_user_id', 'password_reset_tokens', ['user_id'], unique=False)
    op.alter_column('notebooks', 'description',
               existing_type=sa.String(length=1000),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.add_column('notebook_permissions', sa.Column('notify', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('notebook_permissions', sa.Column('can_req_unlock', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('notebook_permissions', sa.Column('can_create', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('notebook_permissions', 'can_request_unlock')
    op.drop_column('notebook_permissions', 'can_comment')
    op.drop_column('notebook_permissions', 'can_attach')
    op.drop_column('notebook_permissions', 'can_export')
    op.drop_column('notebook_permissions', 'can_submit')
    op.add_column('milestones', sa.Column('actual_start_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('milestones', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('milestones', sa.Column('planned_start_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('milestones', sa.Column('sort_order', sa.SMALLINT(), server_default=sa.text("'1'::smallint"), autoincrement=False, nullable=False))
    op.add_column('milestones', sa.Column('actual_end_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('milestones', sa.Column('responsible_person_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_ms_responsible', 'milestones', 'users', ['responsible_person_id'], ['id'])
    op.drop_constraint(None, 'milestone_attachments', type_='foreignkey')
    op.create_foreign_key('milestone_attachments_milestone_id_fkey', 'milestone_attachments', 'milestones', ['milestone_id'], ['id'], ondelete='CASCADE')
    op.add_column('lookup_instruments', sa.Column('location', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_index('ix_lookup_chemicals_name', 'lookup_chemicals', ['chemical_name'], unique=False)
    op.drop_index('ix_exp_root', table_name='experiments')
    op.drop_index('ix_exp_project_status', table_name='experiments')
    op.drop_index('ix_exp_notebook_status', table_name='experiments')
    op.drop_index('ix_exp_latest_version', table_name='experiments')
    op.drop_index('ix_exp_created_at', table_name='experiments')
    op.drop_index('ix_exp_code', table_name='experiments')
    op.create_index('idx_experiments_submitted_to', 'experiments', ['submitted_to'], unique=False)
    op.create_index('idx_experiments_status_latest', 'experiments', ['is_latest_version', 'status'], unique=False)
    op.create_index('idx_experiments_notebook_id', 'experiments', ['notebook_id'], unique=False)
    op.create_index('idx_experiments_created_by', 'experiments', ['created_by'], unique=False)
    op.drop_index('ix_exp_tlc_exp_id', table_name='experiment_tlc')
    op.drop_constraint(None, 'experiment_steps', type_='foreignkey')
    op.create_foreign_key('experiment_steps_experiment_id_fkey', 'experiment_steps', 'experiments', ['experiment_id'], ['id'], ondelete='CASCADE')
    op.drop_index('ix_exp_steps_exp_id', table_name='experiment_steps')
    op.create_index('ix_exp_steps_experiment_id', 'experiment_steps', ['experiment_id'], unique=False)
    op.add_column('experiment_parameters', sa.Column('parameter_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_index('ix_exp_params_exp_id', table_name='experiment_parameters')
    op.alter_column('experiment_parameters', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_index('ix_exp_inputs_exp_id', table_name='experiment_inputs')
    op.alter_column('experiment_inputs', 'moles',
               existing_type=sa.Numeric(precision=14, scale=8),
               type_=sa.NUMERIC(precision=12, scale=6),
               existing_nullable=True)
    op.alter_column('experiment_inputs', 'quantity',
               existing_type=sa.Numeric(precision=12, scale=4),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=True)
    op.alter_column('experiment_inputs', 'cas_no',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.drop_index('ix_exp_hist_exp_id', table_name='experiment_history')
    op.drop_index('ix_exp_hist_action_at', table_name='experiment_history')
    op.drop_constraint(None, 'experiment_excel_templates', type_='foreignkey')
    op.create_foreign_key('experiment_excel_templates_experiment_id_fkey', 'experiment_excel_templates', 'experiments', ['experiment_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'experiment_equipment', type_='foreignkey')
    op.create_foreign_key('experiment_equipment_experiment_id_fkey', 'experiment_equipment', 'experiments', ['experiment_id'], ['id'], ondelete='CASCADE')
    op.drop_index('ix_exp_equip_exp_id', table_name='experiment_equipment')
    op.create_index('ix_exp_equipment_experiment_id', 'experiment_equipment', ['experiment_id'], unique=False)
    op.alter_column('experiment_equipment', 'instrument_code',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_index('ix_exp_comments_exp_id', table_name='experiment_comments')
    op.drop_index('ix_exp_attach_exp_id', table_name='experiment_attachments')
    op.alter_column('departments', 'description',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index('ix_audit_user_at', table_name='audit_log')
    op.drop_index('ix_audit_target', table_name='audit_log')
    op.drop_index('ix_audit_module_at', table_name='audit_log')
    op.drop_index('ix_audit_created_at', table_name='audit_log')
    op.create_index('idx_audit_log_created_at', 'audit_log', ['created_at'], unique=False)
    op.alter_column('audit_log', 'target_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'atr_final_reports', type_='foreignkey')
    op.create_foreign_key('atr_final_reports_atr_id_fkey', 'atr_final_reports', 'atr', ['atr_id'], ['id'], ondelete='CASCADE')
    op.add_column('atr_attachments', sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('atr_attachments', sa.Column('file_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('atr', sa.Column('accepted_by', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('atr', sa.Column('report_type', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('atr', sa.Column('ad_remarks', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('atr', sa.Column('clarification_remarks', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('atr', sa.Column('form_type', sa.VARCHAR(length=50), server_default=sa.text("'STANDARD'::character varying"), autoincrement=False, nullable=False))
    op.add_column('atr', sa.Column('raised_on', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('atr', sa.Column('atr_remarks', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('atr', sa.Column('accepted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('atr', sa.Column('parent_atr_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('atr', sa.Column('is_standalone', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('atr', sa.Column('parent_version_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('atr', sa.Column('clarification_requested_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_atr_accepted_by', 'atr', 'users', ['accepted_by'], ['id'])
    op.create_foreign_key('fk_atr_parent_version', 'atr', 'atr', ['parent_version_id'], ['id'])
    op.create_foreign_key('fk_atr_parent_atr', 'atr', 'atr', ['parent_atr_id'], ['id'])
    op.alter_column('atr', 'objectives',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_table('atr_test_results',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('test_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sort_order', sa.SMALLINT(), server_default=sa.text("'1'::smallint"), autoincrement=False, nullable=False),
    sa.Column('parameter_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('specification', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('value', sa.NUMERIC(precision=20, scale=6), autoincrement=False, nullable=True),
    sa.Column('value_text', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('uom', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('pass_fail', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('result_remarks', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['atr_tests.id'], name='atr_test_results_test_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='atr_test_results_pkey')
    )
    op.create_index('ix_atr_test_results_test_id', 'atr_test_results', ['test_id'], unique=False)
    op.create_table('atr_attributes',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('atr_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('attribute_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('attribute_type', sa.VARCHAR(length=10), server_default=sa.text("'Text'::character varying"), autoincrement=False, nullable=False),
    sa.Column('attribute_value', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('sort_order', sa.SMALLINT(), server_default=sa.text("'1'::smallint"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['atr_id'], ['atr.id'], name='atr_attributes_atr_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='atr_attributes_pkey')
    )
    op.create_index('ix_atr_attributes_atr_id', 'atr_attributes', ['atr_id'], unique=False)
    op.create_table('stage_inputs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('stage_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sort_order', sa.SMALLINT(), server_default=sa.text("'1'::smallint"), autoincrement=False, nullable=False),
    sa.Column('input_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('chemical_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('cas_no', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('mol_wt', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True),
    sa.Column('mol_ratio', sa.NUMERIC(precision=8, scale=4), autoincrement=False, nullable=True),
    sa.Column('density', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True),
    sa.Column('formula', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('strength', sa.NUMERIC(precision=8, scale=2), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='stage_inputs_created_by_fkey'),
    sa.ForeignKeyConstraint(['stage_id'], ['stages.id'], name='stage_inputs_stage_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='stage_inputs_pkey')
    )
    op.create_index('ix_stage_inputs_stage_id', 'stage_inputs', ['stage_id'], unique=False)
    op.create_table('atr_tests',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('atr_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sample_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('test_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('sub_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('ar_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=True),
    sa.Column('quantity_unit', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('priority', sa.VARCHAR(length=20), server_default=sa.text("'Medium'::character varying"), autoincrement=False, nullable=False),
    sa.Column('specification', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('remarks', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('team', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=30), server_default=sa.text("'NEW'::character varying"), autoincrement=False, nullable=False),
    sa.Column('assigned_to', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('assigned_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('analyzed_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('analyzed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('verified_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('verified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('accepted_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('accepted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('accepted_remarks', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('unsatisfactory_remarks', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['accepted_by'], ['users.id'], name='atr_tests_accepted_by_fkey'),
    sa.ForeignKeyConstraint(['analyzed_by'], ['users.id'], name='atr_tests_analyzed_by_fkey'),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], name='atr_tests_assigned_to_fkey'),
    sa.ForeignKeyConstraint(['atr_id'], ['atr.id'], name='atr_tests_atr_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sample_id'], ['atr_samples.id'], name='atr_tests_sample_id_fkey'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], name='atr_tests_verified_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='atr_tests_pkey')
    )
    op.create_index('ix_atr_tests_atr_id', 'atr_tests', ['atr_id'], unique=False)
    op.create_table('project_parameter_templates',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sort_order', sa.SMALLINT(), server_default=sa.text("'1'::smallint"), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('parameter_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('input_output', sa.VARCHAR(length=10), server_default=sa.text("'INPUT'::character varying"), autoincrement=False, nullable=False),
    sa.Column('user_entered_or_formula', sa.VARCHAR(length=20), server_default=sa.text("'USER ENTERED'::character varying"), autoincrement=False, nullable=False),
    sa.Column('param_type', sa.VARCHAR(length=10), server_default=sa.text("'NUMBER'::character varying"), autoincrement=False, nullable=False),
    sa.Column('formula', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('uom', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='project_parameter_templates_created_by_fkey'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='project_parameter_templates_project_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='project_parameter_templates_pkey')
    )
    op.create_index('ix_proj_param_tmpl_project_id', 'project_parameter_templates', ['project_id'], unique=False)
    op.create_table('milestone_predecessors',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('milestone_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('predecessor_milestone_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], name='milestone_predecessors_milestone_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['predecessor_milestone_id'], ['milestones.id'], name='milestone_predecessors_predecessor_milestone_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='milestone_predecessors_pkey')
    )
    op.create_table('project_attributes',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('attribute_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('attribute_type', sa.VARCHAR(length=10), server_default=sa.text("'TEXT'::character varying"), autoincrement=False, nullable=False),
    sa.Column('attribute_value', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='project_attributes_created_by_fkey'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='project_attributes_project_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='project_attributes_updated_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='project_attributes_pkey')
    )
    op.create_index('ix_project_attrs_project_id', 'project_attributes', ['project_id'], unique=False)
    op.create_table('atr_samples',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('atr_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sample_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('sample_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('batch_no', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=True),
    sa.Column('quantity_unit', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('mfg_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('expiry_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('storage_condition_period', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('packing', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=30), server_default=sa.text("'In-Process'::character varying"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['atr_id'], ['atr.id'], name='atr_samples_atr_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='atr_samples_pkey')
    )
    op.create_index('ix_atr_samples_atr_id', 'atr_samples', ['atr_id'], unique=False)
    # ### end Alembic commands ###
