"""Inventory – Master Templates: downloadable Excel templates served from disk (Phase 4).

Templates live under backend/uploads/excel_templates/ so this works fully
offline on an intranet deployment. Generated once (idempotent) on first
import if missing.
"""
import os
from typing import Any

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import FileResponse

from app.dependencies import get_current_user

router = APIRouter(prefix="/inventory/master-templates", tags=["inventory-master-templates"])

TEMPLATES_DIR = os.environ.get(
    "MASTER_TEMPLATES_DIR",
    os.path.join(os.path.dirname(__file__), "..", "..", "..", "uploads", "excel_templates"),
)

TEMPLATES = [
    {"key": "maintenance-planner", "name": "Maintenance Planner Template", "filename": "maintenance_planner_template.xlsx"},
    {"key": "calibration-planner", "name": "Calibration Planner Template", "filename": "calibration_planner_template.xlsx"},
    {"key": "materials", "name": "Materials Bulk Upload Template", "filename": "materials_template.xlsx"},
    {"key": "manufacturers", "name": "Manufacturers Bulk Upload Template", "filename": "manufacturers_template.xlsx"},
    {"key": "mappings", "name": "Manufacturer Mapping Bulk Upload Template", "filename": "mappings_template.xlsx"},
]


TEMPLATE_SHEETS = {
    "maintenance-planner": {
        "headers": ["Equipment Code", "Schedule Type", "Due Date"],
        "example": ["e.g. CPL/MFG/FBE-110", "MONTHLY", "2026-12-31"],
        "widths": (28, 16, 14),
    },
    "calibration-planner": {
        "headers": ["Instrument Code", "Schedule Type", "Due Date"],
        "example": ["e.g. CPL/MFG/FBE-110", "MONTHLY", "2026-12-31"],
        "widths": (28, 16, 14),
    },
    "materials": {
        # Code is intentionally excluded: it is always auto-generated by the
        # backend on upload, same as the single-material create form.
        "headers": [
            "Name", "Material Type", "CAS No", "Molecular Formula",
            "Mol. Weight (g/mol)", "Storage Condition", "Hazard Class",
            "Consumable Type", "Description",
        ],
        "example": [
            "Acetonitrile HPLC Grade", "RAW MATERIAL", "75-05-8", "C2H3N",
            "41.05", "RT", "Flammable",
            "", "Mobile phase solvent for HPLC analysis",
        ],
        "widths": (28, 20, 16, 18, 16, 18, 18, 18, 32),
    },
    "manufacturers": {
        # Unlike Materials, Manufacturer codes are NOT auto-generated — Code is
        # required and must be supplied by the uploader, matching the single
        # create form's behavior.
        "headers": [
            "Code", "Name", "Country", "Contact Person",
            "Email", "Phone", "Website", "Address",
        ],
        "example": [
            "SIG", "Sigma-Aldrich (Merck)", "USA", "Sales Desk",
            "orders@sigmaaldrich.com", "+1-800-325-3010", "www.sigmaaldrich.com", "",
        ],
        "widths": (14, 28, 16, 20, 26, 18, 24, 30),
    },
    "mappings": {
        # Material/Manufacturer are resolved by their existing Code on upload —
        # both must already exist (create them first via their own bulk upload).
        "headers": [
            "Material Code", "Manufacturer Code", "Catalogue No",
            "Technical Grade", "Lead Time (days)", "Min Order Qty",
        ],
        "example": ["MAT/26/100008", "SIG", "SIG-12345", "HPLC", "14", "5"],
        "widths": (20, 20, 18, 18, 18, 16),
    },
}


def _ensure_templates() -> None:
    os.makedirs(TEMPLATES_DIR, exist_ok=True)
    from openpyxl import Workbook
    from openpyxl.utils import get_column_letter

    for t in TEMPLATES:
        path = os.path.join(TEMPLATES_DIR, t["filename"])
        if os.path.isfile(path):
            continue
        sheet = TEMPLATE_SHEETS[t["key"]]
        wb = Workbook()
        ws = wb.active
        ws.title = "Template"
        ws.append(sheet["headers"])
        ws.append(sheet["example"])
        for i, width in enumerate(sheet["widths"], start=1):
            ws.column_dimensions[get_column_letter(i)].width = width
        wb.save(path)


_ensure_templates()


@router.get("")
def list_templates(_: Any = Depends(get_current_user)):
    return TEMPLATES


@router.get("/{key}/download")
def download_template(key: str, _: Any = Depends(get_current_user)):
    match = next((t for t in TEMPLATES if t["key"] == key), None)
    if not match:
        raise HTTPException(404, "Template not found.")
    path = os.path.join(TEMPLATES_DIR, match["filename"])
    if not os.path.isfile(path):
        _ensure_templates()
    return FileResponse(path, filename=match["filename"], media_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")
