/**
 * Fine-grained (department, role) privilege keys referenced from frontend code.
 *
 * Must mirror backend-node/src/shared/privilegeCatalog.ts — that file is the
 * source of truth and the admin matrix UI is driven by its API response, so this
 * union exists purely to catch typos at compile time in `useCan(...)` calls.
 */
export type AdcPrivilege =
  | 'adc.module.access'
  | 'adc.dashboard.hod'
  | 'adc.dashboard.tl'
  | 'adc.dashboard.chemist'
  | 'adc.project.create'
  | 'adc.project.view'
  | 'adc.project.view_all'
  | 'adc.project.edit'
  | 'adc.project.close'
  | 'adc.project.reopen'
  | 'adc.project.deactivate'
  | 'adc.project.manage_members'
  | 'adc.project.manage_attachments'
  | 'adc.project.risk_assessment_edit'
  | 'adc.workflow_templates.manage'
  | 'adc.calc_templates.manage'
  | 'adc.notebook.create'
  | 'adc.notebook.view'
  | 'adc.notebook.view_all'
  | 'adc.notebook.edit'
  | 'adc.notebook.assign_user'
  | 'adc.notebook.close'
  | 'adc.notebook.reopen'
  | 'adc.notebook.deactivate'
  | 'adc.experiment.create'
  | 'adc.experiment.view'
  | 'adc.experiment.view_all'
  | 'adc.experiment.edit'
  | 'adc.experiment.assign_user'
  | 'adc.experiment.submit'
  | 'adc.experiment.approve'
  | 'adc.experiment.reject'
  | 'adc.experiment.unlock'
  | 'adc.experiment.void'
  | 'adc.experiment.clone'
  | 'adc.experiment.sign_done'
  | 'adc.experiment.sign_checked'
  | 'adc.experiment.manage_files'
  | 'adc.experiment.raise_atr'
  | 'adc.experiment.submit_to_ad'
  | 'adc.experiment.risk_assessment_approve'

/**
 * Mirrors the CGT half of backend-node/src/shared/privilegeCatalog.ts.
 */
export type CgtPrivilege =
  | 'cgt.module.access'
  | 'cgt.dashboard.hod'
  | 'cgt.dashboard.tl'
  | 'cgt.dashboard.analyst'
  | 'cgt.project.create'
  | 'cgt.project.view'
  | 'cgt.project.view_all'
  | 'cgt.project.edit'
  | 'cgt.project.close'
  | 'cgt.project.reopen'
  | 'cgt.project.deactivate'
  | 'cgt.project.manage_members'
  | 'cgt.project.manage_attachments'
  | 'cgt.project.risk_assessment_edit'
  | 'cgt.workflow_templates.manage'
  | 'cgt.calc_templates.manage'
  | 'cgt.notebook.create'
  | 'cgt.notebook.view'
  | 'cgt.notebook.view_all'
  | 'cgt.notebook.edit'
  | 'cgt.notebook.assign_user'
  | 'cgt.notebook.close'
  | 'cgt.notebook.reopen'
  | 'cgt.notebook.deactivate'
  | 'cgt.experiment.create'
  | 'cgt.experiment.view'
  | 'cgt.experiment.view_all'
  | 'cgt.experiment.edit'
  | 'cgt.experiment.assign_user'
  | 'cgt.experiment.submit'
  | 'cgt.experiment.approve'
  | 'cgt.experiment.reject'
  | 'cgt.experiment.unlock'
  | 'cgt.experiment.void'
  | 'cgt.experiment.clone'
  | 'cgt.experiment.sign_done'
  | 'cgt.experiment.sign_checked'
  | 'cgt.experiment.manage_files'
